# convert json to string

In [2]:
import pandas as pd
from io import StringIO as si

# Sample JSON string
data = '''
[
  {"id": 1, "name": "Ankit Roy", "age": 21, "department": "CSE", "cgpa": 8.5},
  {"id": 2, "name": "Sneha Das", "age": 20, "department": "ECE", "cgpa": 9.1},
  {"id": 3, "name": "Rahul Sen", "age": 22, "department": "ME", "cgpa": 7.8},
  {"id": 4, "name": "Priya Sharma", "age": 21, "department": "IT", "cgpa": 8.9}
]
'''
# Convert string to file-like object and read
df = pd.read_json(si(data))
print(df)
print(type(df))

   id          name  age department  cgpa
0   1     Ankit Roy   21        CSE   8.5
1   2     Sneha Das   20        ECE   9.1
2   3     Rahul Sen   22         ME   7.8
3   4  Priya Sharma   21         IT   8.9
<class 'pandas.core.frame.DataFrame'>

# string to json

In [3]:
df.to_json()

'{"id":{"0":1,"1":2,"2":3,"3":4},"name":{"0":"Ankit Roy","1":"Sneha Das","2":"Rahul Sen","3":"Priya Sharma"},"age":{"0":21,"1":20,"2":22,"3":21},"department":{"0":"CSE","1":"ECE","2":"ME","3":"IT"},"cgpa":{"0":8.5,"1":9.1,"2":7.8,"3":8.9}}'

# using orintation

In [4]:
df.to_json(orient='records')

'[{"id":1,"name":"Ankit Roy","age":21,"department":"CSE","cgpa":8.5},{"id":2,"name":"Sneha Das","age":20,"department":"ECE","cgpa":9.1},{"id":3,"name":"Rahul Sen","age":22,"department":"ME","cgpa":7.8},{"id":4,"name":"Priya Sharma","age":21,"department":"IT","cgpa":8.9}]'

In [5]:
# it is defult
df.to_json(orient='index')

'{"0":{"id":1,"name":"Ankit Roy","age":21,"department":"CSE","cgpa":8.5},"1":{"id":2,"name":"Sneha Das","age":20,"department":"ECE","cgpa":9.1},"2":{"id":3,"name":"Rahul Sen","age":22,"department":"ME","cgpa":7.8},"3":{"id":4,"name":"Priya Sharma","age":21,"department":"IT","cgpa":8.9}}'

# read for a link

# read a json using url

In [6]:
import pandas as pd

d = pd.read_json('https://jsonplaceholder.typicode.com/users')
d.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

# read html file

In [7]:
pip install lxml

Collecting lxml
  Downloading lxml-6.0.2-cp313-cp313-macosx_10_13_x86_64.whl.metadata (3.6 kB)
Downloading lxml-6.0.2-cp313-cp313-macosx_10_13_x86_64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 4.0 MB/s  0:00:01 eta 0:00:01
Installing collected packages: lxml
Successfully installed lxml-6.0.2

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:

import pandas as pd
url = "https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"
tables = pd.read_html(url)

# Print the number of tables and show the first one
print(f"Total tables found: {len(tables)}")
tables[0].head()

Total tables found: 1

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524

In [9]:
pip install pandas openpyxl

Requirement already satisfied: pandas in /Users/apple/AI_ML/.venv/lib/python3.13/site-packages (2.3.1)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: numpy>=1.26.0 in /Users/apple/AI_ML/.venv/lib/python3.13/site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/apple/AI_ML/.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/apple/AI_ML/.venv/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/apple/AI_ML/.venv/lib/python3.13/site-packages (from pandas) (2025.2)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in /Users/apple/AI_ML/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

# excel file

## make an excel file and read it

In [10]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 27, 22],
    'City': ['New York', 'San Francisco', 'Chicago']
}
df1 = pd.DataFrame(data)
df1.to_excel('my_data.xlsx', index=False)
# read it 
df1 = pd.read_excel('my_data.xlsx')
df1

      Name  Age           City
0    Alice   24       New York
1      Bob   27  San Francisco
2  Charlie   22        Chicago

## convert this in a pickle file

In [11]:
df1.to_pickle('df1')

## read this file

In [12]:
pd.read_pickle('df1')

      Name  Age           City
0    Alice   24       New York
1      Bob   27  San Francisco
2  Charlie   22        Chicago

In [13]:
data = [
  {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz"
  },
  {
    "id": 2,
    "name": "Ervin Howell",
    "username": "Antonette",
    "email": "Shanna@melissa.tv"
  }
]
d = pd.DataFrame(data)
d

   id           name   username              email
0   1  Leanne Graham       Bret  Sincere@april.biz
1   2   Ervin Howell  Antonette  Shanna@melissa.tv